### ISSUE TITLE
mypy type errors

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/galois-py-toolkit#2]
To reproduce, enter a `virtualenv`, install the dependencies, and run:

```
$ mypy cryptol saw tests
tests/cryptol/test_cryptol_api.py:7: error: Skipping analyzing 'BitVector': found module but no type hints or library stubs
tests/cryptol/test_cryptol_api.py:7: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
tests/cryptol/test_cryptol_api.py:40: error: Cannot find implementation or library stub for module named 'Foo'
saw/connection.py:34: error: Argument 1 to "getpgid" has incompatible type "Optional[int]"; expected "int"
saw/__init__.py:137: error: Argument 1 to "getpgid" has incompatible type "Optional[int]"; expected "int"
saw/__init__.py:145: error: Function is missing a return type annotation
tests/saw/test_salsa20_easy.py:60: error: Argument 1 to "__call__" of "CryptolTerm" has incompatible type "List[FreshVar]"; expected "CryptolJSON"
Found 6 errors in 4 files (checked 28 source files)
```

**Comment by pnwamk** [comment]
Mypy errors fixed via 6b97257534e4bfb579490712588d960122738688 and now a part of CI :+1:

**Comment by RyanGlScott** [comment]
Thanks! Do you think it's worth running the test suite through `mypy` as well? Currently, I get this:

```
$ mypy tests
tests/cryptol/test_cryptol_api.py:7: error: Skipping analyzing 'BitVector': found module but no type hints or library stubs
tests/cryptol/test_cryptol_api.py:7: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
tests/cryptol/test_cryptol_api.py:32: error: Cannot find implementation or library stub for module named 'Foo'
tests/saw/test_salsa20_easy.py:59: error: Argument 1 to "__call__" of "CryptolTerm" has incompatible type "List[FreshVar]"; expected "CryptolJSON"
Found 3 errors in 2 files (checked 15 source files)
```

**Comment by pnwamk** [comment]
Ah, probably yes! =)

**Comment by RyanGlScott** [comment]
* The error at `tests/cryptol/test_cryptol_api.py:7` is caused by the `BitVector` library not having typing annotations, so that's easily worked around with `#type: ignore`.
* The error at `tests/cryptol/test_cryptol_api.py:32` is caused by some especially dynamically typed code:

  https://github.com/GaloisInc/galois-py-toolkit/blob/fa2ecc1063445d871f04a5d6b8fad31233755155/tests/cryptol/test_cryptol_api.py#L31-L32

   Under the hood, `add_cryptol_module` adds another module to `sys.modules`. Based off of python/mypy#8683, this doesn't appear to be a pattern that `mypy` can support, so I don't think we have much of a choice besides suppressing the error wth `#type: ignore`.
* The error at `tests/saw/test_salsa20_easy.py:59` is more interesting:

  https://github.com/GaloisInc/galois-py-toolkit/blob/fa2ecc1063445d871f04a5d6b8fad31233755155/tests/saw/test_salsa20_easy.py#L59

  Indeed, `[y0, y1, y2, y3]` isn't an instance of `CryptolJSON` at a glance. This makes me wonder how this code is working currently...

**Comment by pnwamk** [comment]
I just spent a few minutes looking into this. The first two issues you noted are fixed pretty trivially by just ignoring the types or lack thereof. (I think that's the reasonable thing to do there at least, given that both don't have type annotations.)

The last type issue led me on a little journey... it seems like if we want to have nice and clean Pythonic code, then we need to be able to seamlessly use Python data structures when it makes sense to do so (e.g., lists in this case). To describe this, you _must_ have recursive types, and interestingly that seems like an all but abandoned mypy feature at this point. However, other type checkers seem to support this (e.g., [Pyright](https://github.com/microsoft/pyright) [here](https://github.com/microsoft/pyright/issues/569))... so I need to dig more and get back to this methinks.

**Comment by pnwamk** [comment]
Moved https://github.com/GaloisInc/saw-script/issues/1125
